import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner"
import QueryProviders from "@/providers/query-provider";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  style: "normal",
})

export const metadata: Metadata = {
  title: "LoopIn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TooltipProvider>
        <body className={`${nunitoSans.className}`}>
          <QueryProviders>
            <main>{children}</main>
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: "#ffffff",
                  color: "#000000",
                },
                duration: 3000,
              }}
            />
          </QueryProviders>
        </body>
      </TooltipProvider>
    </html>
  );
}
