import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import {Toaster} from "@/components/ui/sonner"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  style: "normal",
})

export const metadata: Metadata = {
  title: "LoopIn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TooltipProvider>
        <body
          className={`${nunitoSans.className}`}
        >
          <main>{children}</main>
          <Toaster 
            position="top-right"
            toastOptions={{
              style: {
                background: "#ffffff",
                color: "#000000",
              },
              duration: 3000,
            }}
          /> 
        </body>
      </TooltipProvider>
    </html>
  );
}
